SELECT CONCAT(name, '(', SUBSTR(OCCUPATION,1,1), ')')
FROM OCCUPATIONS
ORDER BY NAME ASC;

SELECT CONCAT('There are a total of ', COUNT(1), ' ' , LOWER(OCCUPATION), 's.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(1) ASC, OCCUPATION ASC;
